# Generated by Django 3.2 on 2020-10-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mymodel',
            new_name='whoever',
        ),
    ]
