# Generated by Django 3.2 on 2020-11-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_rename_mymodel_whoever'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('years_old', models.IntegerField()),
                ('hairColor', models.CharField(max_length=10)),
            ],
        ),
    ]
