# Generated by Django 3.2 on 2021-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_client_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='coin',
            field=models.CharField(blank=None, default='Dollar', max_length=20, null=True),
        ),
    ]
